version: 0.2 
run-as: root
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo $CODEBUILD_SRC_DIR
  pre_build:
    commands:
      - echo Installing flutter dependencies
      - export FLUTTER_SDK=$CODEBUILD_SRC_DIR/flutter-sdk
      - mkdir $FLUTTER_SDK
      - git clone https://github.com/flutter/flutter.git $FLUTTER_SDK -b stable
      - export PATH="$PATH:$FLUTTER_SDK/bin"
      - flutter precache
      - flutter doctor
      - flutter upgrade
      - flutter pub get
  build:
    commands:
      - echo Build started
      - flutter build apk
post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - build/app/outputs/apk/release/*.apk
  discard-paths: yes
