version: 0.2
run-as: root
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo $CODEBUILD_SRC_DIR
  pre_build:
    commands:
      - flutter doctor
      - ls
  build:
    commands:
      - echo Build started
      - flutter build apk
post_build:
  commands:
    - echo Build completed
artifacts:
  files:
    - build/app/outputs/apk/release/appbuild.apk
  discard-paths: yes
