version: 0.2
run-as: root
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo $CODEBUILD_SRC_DIR
  pre_build:
    commands:
      - flutter doctor
      - ls
  build:
    commands:
      - echo Build started
      - git config --global --add safe.directory /home/mobiledevops/.flutter-sdk
      - dart --version
      - flutter upgrade
      - dart --version
      - flutter build apk
      - mkdir new 
      - mv build/app/outputs/flutter-apk/app-release.apk new
      - ls
post_build:
  commands:
    - echo Build completed
artifacts:
  secondary-artifacts:
  artifact1:
    base-directory: new
    files:
      - "**/*"
  artifact2:
    base-directory: new
    files:
      - "**/*" 


  
